version: "3.8"
services:
  jenkins-master:
    image: oavramenk/jenkins-master:1.0
    env_file: .env
    restart: always
    environment:
      - JENKINS_ADMINISTRATOR_USERNAME
      - JENKINS_ADMINISTRATOR_PASSWORD
      - JENKINS_ADMINISTRATOR_EMAIL=admin@mail.com
      - JENKINS_URL=localhost:8080
      - TZ=UTC
    ports:
      - "8080:8080"
      - "50000:50000"
    user: jenkins:jenkins
    volumes:
      - "jenkins_master_data:/var/jenkins_home"
    networks: 
      - jenkins
  docker-agent-1:
    image: oavramenk/jenkins-agent:1.0
    restart: always
    environment:
      - JENKINS_AGENT_USERNAME
      - JENKINS_AGENT_PASSWORD
      - JENKINS_MASTER_HOST_INTERNAL=jenkins-master
      - JENKINS_MASTER_PORT=8080
      - NAME=docker-agent-1
    user: jenkins-agent:998 # id of docker group on the host
    depends_on: 
      - jenkins-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker_agent_1_data:/jenkins-agent
    networks: 
      - jenkins

  backup:
    image: offen/docker-volume-backup:v2
    restart: always
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_RETENTION_DAYS: 7
      BACKUP_CRON_EXPRESSION: 0 */6 * * *
    volumes:
      - jenkins_master_data:/backup/jenkins-data:ro     # Mount the Jenkins data volume (as read-only)
      - /opt/jenkins-backups:/archive                       # Mount a local folder as the backup archive

#  -------------------  Agents for old jobs ----------------------
# To be removed after migration to pipelines will be completed

  java-11-agent:
    image: oavramenk/java-jenkins-agent:11
    restart: always
    environment:
      - JENKINS_AGENT_USERNAME
      - JENKINS_AGENT_PASSWORD
      - JENKINS_MASTER_HOST_INTERNAL=jenkins-master
      - JENKINS_MASTER_PORT=8080
      - NAME=java-11-agent
    depends_on: 
      - jenkins-master
    volumes:
      - java-11-agent:/jenkins-agent
    networks: 
      - jenkins

  ansible-agent:
    image: oavramenk/ansible-jenkins-agent:2.9
    restart: always
    environment:
      - JENKINS_AGENT_USERNAME
      - JENKINS_AGENT_PASSWORD
      - JENKINS_MASTER_HOST_INTERNAL=jenkins-master
      - JENKINS_MASTER_PORT=8080
      - NAME=ansible-agent
    depends_on: 
      - jenkins-master
    volumes:
      - ansible-agent:/jenkins-agent
    networks: 
      - jenkins

  node8-agent:
    image: oavramenk/node-jenkins-agent:8.15
    restart: always
    environment:
      - JENKINS_AGENT_USERNAME
      - JENKINS_AGENT_PASSWORD
      - JENKINS_MASTER_HOST_INTERNAL=jenkins-master
      - JENKINS_MASTER_PORT=8080
      - NAME=node8-agent
    depends_on: 
      - jenkins-master
    volumes:
      - node8-agent:/jenkins-agent
    networks: 
      - jenkins
    
# -----------------------------------------------------------------------

volumes:
  jenkins_master_data:
    driver: local
  docker_agent_1_data:
    driver: local
# Volumes for old jobs.
# To be removed after migration to pipelines will be completed
  java-11-agent:
    driver: local
  ansible-agent:
    driver: local
  node8-agent:
    driver: local

networks:
  jenkins:
    driver: bridge
