version: "3"
services:
  master:
    build: ./master
    env_file: .env
    environment:
      - JENKINS_ADMINISTRATOR_USERNAME
      - JENKINS_ADMINISTRATOR_PASSWORD
    ports:
      - "8080:8080"
  slave:
    build: ./slave
    environment:
      - REGISTRY_HOST=localhost:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - master
  registry:
    image: registry:2
    ports:
      - "5000:5000"
