FROM ubuntu:18.04

COPY ./install-envsubst.sh .
COPY ./install-java.sh .
COPY ./install-ansible.sh .
COPY ./install-node.sh .

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
  apt-get install -y apt-utils sshpass curl openjdk-11-jdk-headless git curl wget maven && \
  ./install-ansible.sh && \
  ./install-node.sh && \
  ./install-envsubst.sh && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /jenkins-agent

COPY ./node.xml.template .
COPY ./wait-for-it.sh .
COPY ./entrypoint.sh .

ENTRYPOINT ["./entrypoint.sh"]